Repository thoth-station/cve-update-job, pull requests merged in 2018-09, with the labels that each got.

#27 Fix indentation in the cronjob template
  openshift/cronJob-template.yaml
Labels: size/XS

#28 Automatic update of dependency thoth-storages from 0.5.1 to 0.5.2
  Pipfile.lock
Labels: bot

#29 Automatic update of dependency thoth-common from 0.2.5 to 0.2.6
  Pipfile.lock
Labels: bot

#30 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#32 Automatic update of dependency pytest-cov from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot

#36 Automatic update of dependency thoth-common from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#38 Automatic update of dependency pytest from 3.8.0 to 3.8.1
  Pipfile.lock
Labels: bot

#40 Automatic update of dependency thoth-common from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot

#42 Automatic update of dependency thoth-common from 0.3.2 to 0.3.5
  Pipfile.lock
Labels: bot

#45 Automatic update of dependency thoth-common from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot

#44 Update README file
  README.rst
Labels: approved, size/S
