Repository thoth-station/cve-update-job, pull requests merged in 2018-08, with the labels that each got.

#2 Initial dependency lock
  Pipfile.lock
Labels: approved, bot, size/L

#4 OpenShift templates
  Pipfile
  Pipfile.lock
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: size/L

#6 Fix image stream name
  openshift/imageStream-template.yaml
Labels: size/XS

#7 Fix cronjob template name
  openshift/cronJob-template.yaml
Labels: size/XS

#8 Print version specification with resolved log
  app.py
Labels: size/XS

#16 Store information about CVEs
  app.py
Labels: approved, size/S

#19 Add .coafile for coala
  .coafile
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L, size/S

#20 Automatic update of dependency thoth-common from 0.2.2 to 0.2.4
  Pipfile.lock
Labels: bot

#17 Automatic update of dependency thoth-storages from 0.5.0 to 0.5.1
  Pipfile.lock
Labels: bot

#21 Add LICENSE file
  LICENSE
Labels: approved, size/XL

#22 Automatic update of dependency pytest from 3.7.3 to 3.7.4
  Pipfile.lock
Labels: bot

#24 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot
