Repository thoth-station/cve-update-job, pull requests merged in 2019-02, with the labels that each got.

#105 Automatic update of dependency pytest from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#106 Update year in sources
  app.py
Labels: size/XS

#107 Ignore index in solver output
  app.py
Labels: size/XS

#109 Automatic update of dependency pytest from 4.2.0 to 4.2.1
  Pipfile.lock
Labels: bot

#108 Rely on normalized name provided by resolver
  app.py
Labels: approved, size/M

#111 Automatic update of dependency thoth-storages from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#112 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#113 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot
