Repository thoth-station/cve-update-job, pull requests merged in 2019-07, with the labels that each got.

#156 Document how to run job locally
  README.rst
Labels: approved, size/S

#158 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.8
  Pipfile.lock
Labels: bot

#159 Automatic update of dependency thoth-solver from 1.1.0 to 1.2.1
  Pipfile.lock
Labels: bot

#160 Automatic update of dependency thoth-common from 0.9.0 to 0.9.3
  Pipfile.lock
Labels: bot

#161 Automatic update of dependency pytest from 4.6.3 to 5.0.1
  Pipfile.lock
Labels: bot

#162 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#163 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#164 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency thoth-solver from 1.2.1 to 1.2.2
  Pipfile.lock
Labels: bot

#166 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#168 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#169 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#170 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
