Repository thoth-station/cve-update-job, pull requests merged in 2019-03, with the labels that each got.

#116 Normalize Python package names
  app.py
Labels: size/XS

#117 Automatic update of dependency pytest from 4.3.0 to 4.3.1
  Pipfile.lock
Labels: bot

#118 added image stream tag and namespace parameter
  .coafile
  .zuul.yaml
  openshift/cronJob-template.yaml
Labels: size/M

#120 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#122 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#123 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#124 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
