Repository thoth-station/cve-update-job, pull requests merged in 2019-11, with the labels that each got.

#226 Stop using starting deadline seconds
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#228 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#229 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#230 Automatic update of dependency thoth-solver from 1.2.2 to 1.4.0
  Pipfile.lock
Labels: bot

#231 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#232 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#233 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#234 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/M

#235 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/S

#236 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/S

#237 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.22
  Pipfile.lock
Labels: bot, size/S

#238 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#239 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#240 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/M

#241 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#242 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#243 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M

#244 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS
