Repository thoth-station/cve-update-job, pull requests merged in 2019-01, with the labels that each got.

#100 Fix import error, module has moved
  app.py
Labels: approved, size/XS

#101 Skip package if there was an error in resolution
  app.py
Labels: size/M, size/XS

#103 Automatic update of dependency pytest-cov from 2.6.0 to 2.6.1
  Pipfile.lock
Labels: bot

#102 Automatic update of dependency pytest from 4.0.2 to 4.1.1
  Pipfile.lock
Labels: bot

#104 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
