Repository thoth-station/cve-update-job, pull requests merged in 2019-10, with the labels that each got.

#208 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#209 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#210 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#211 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#212 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#213 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#217 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#220 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#221 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#222 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#223 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#224 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#225 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
