Repository thoth-station/cve-update-job, pull requests merged in 2020-07, with the labels that each got.

#349 include github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .thoth.yaml
Labels: approved, size/M

#350 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#352 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#353 Automatic update of dependency thoth-common from 0.13.8 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#356 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot

#358 Solver does not take all_versions parameter anymore
  app.py
Labels: approved, size/XS

#348 enable pre-commit support for the application
  .coafile
  .gitignore
  .pre-commit-config.yaml
  .thothTemplate.yaml
  README.rst
  app.py
Labels: approved, size/L

#363 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.1
  Pipfile.lock
Labels: approved, bot

#364 Automatic update of dependency thoth-storages from 0.24.1 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/XS

#351 migrate manifest for the application to config app
  .zuul.yaml
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#365 Added version file
  app.py
Labels: approved, do-not-merge/work-in-progress, size/XS

#368 Release of version 0.2.0
  CHANGELOG.md
  app.py
Labels: approved, bot, size/L

#370 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#371 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/L
