Repository thoth-station/cve-update-job, pull requests merged in 2020-11, with the labels that each got.

#385 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#386 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/L

#391 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/XS

#393 port to python 38
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#394 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#396 update aicoe-ci configuration for cve-update-job
  .aicoe-ci.yaml
Labels: approved, size/S

#397 update .aicoe-ci.yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
