Repository thoth-station/cve-update-job, pull requests merged in 2020-04, with the labels that each got.

#322 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#323 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/S

#324 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#325 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#326 Automatic update of dependency thoth-common from 0.12.7 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#327 Automatic update of dependency thoth-solver from 1.5.1 to 1.5.2
  Pipfile.lock
Labels: bot, size/L

#328 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#329 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/S

#330 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/S

#331 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/M

#332 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#333 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
