Repository thoth-station/cve-update-job, pull requests merged in 2020-10, with the labels that each got.

#375 Automatic update of dependency thoth-common from 0.14.2 to 0.20.2
  Pipfile.lock
Labels: approved, bot

#376 Automatic update of dependency thoth-solver from 1.5.2 to 1.6.0
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/S

#377 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.15
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#378 Automatic update of dependency pytest from 5.4.3 to 6.1.1
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#379 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/XL

#382 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/XS

#374 make cve-update-job kafka producer
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/L
