Repository thoth-station/cve-update-job, pull requests merged in 2020-01, with the labels that each got.

#256 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#257 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#259 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#260 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/M

#261 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#262 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/M

#265 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#258 Happy new year!
  app.py
Labels: approved, size/XS

#266 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#263 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#267 Automatic update of dependency thoth-solver from 1.4.1 to 1.5.0
  Pipfile.lock
Labels: bot, size/S

#268 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#269 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#270 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#271 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#272 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/S

#273 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/L

#274 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#275 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#276 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#277 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#278 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#280 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#281 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/M

#282 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/M

#283 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#284 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/XS

#285 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/XS

#287 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#288 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/L

#289 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/S

#290 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#291 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#293 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M

#294 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
