Repository thoth-station/cve-update-job, pull requests merged in 2021-06, with the labels that each got.

#409 add prow and remove pre-commit from aicoe-ci
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, size/M

#405 Start using pypa/advisory-db as a source of CVEs
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/XXL

#410 Add metrics for CVE update job
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/L

#418 set badges for easy access to content
  README.rst
Labels: approved, size/XS
