Repository thoth-station/cve-update-job, pull requests merged in 2022-11, with the labels that each got.

#490 git ls-files -z -- .pre-commit-config.yaml | xargs -0 sed -i 's#https://gitlab.com/PyCQA/flake8#https://github.com/PyCQA/flake8#'
  .pre-commit-config.yaml
Labels: approved, lgtm

#491 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#495 Migrate flake8 settings to .flake8 file
  .flake8
  .pre-commit-config.yaml
Labels: approved, size/S, lgtm

#494 Fix metrics overflow
  app.py
Labels: approved, size/M, lgtm
